[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings=[
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
    "@account-abstraction/contracts=lib/account-abstraction/contracts",
    "@zkaccount-abstraction/contracts/=lib/foundry-era-contracts/src/system-contracts/contracts/"
]
via-ir = true